/framefab_mpp/wire_frame_collision_start_vertex_color_r: 0
/framefab_mpp/wire_frame_collision_start_vertex_color_g: 255
/framefab_mpp/wire_frame_collision_start_vertex_color_b: 0
/framefab_mpp/wire_frame_collision_start_vertex_color_a: 1

/framefab_mpp/wire_frame_collision_end_vertex_color_r: 255
/framefab_mpp/wire_frame_collision_end_vertex_color_g: 0
/framefab_mpp/wire_frame_collision_end_vertex_color_b: 0
/framefab_mpp/wire_frame_collision_end_vertex_color_a: 1

/framefab_mpp/wire_frame_collision_cylinder_color_r: 122
/framefab_mpp/wire_frame_collision_cylinder_color_g: 122
/framefab_mpp/wire_frame_collision_cylinder_color_b: 122
/framefab_mpp/wire_frame_collision_cylinder_color_a: 0.25
