wire_frame_collision_start_vertex_color_r: 0
wire_frame_collision_start_vertex_color_g: 255
wire_frame_collision_start_vertex_color_b: 0
wire_frame_collision_start_vertex_color_a: 1

wire_frame_collision_end_vertex_color_r: 255
wire_frame_collision_end_vertex_color_g: 0
wire_frame_collision_end_vertex_color_b: 0
wire_frame_collision_end_vertex_color_a: 1

wire_frame_collision_cylinder_color_r: 122
wire_frame_collision_cylinder_color_g: 122
wire_frame_collision_cylinder_color_b: 122
wire_frame_collision_cylinder_color_a: 0.25
